#! /usr/bin/env bash

set -euo pipefail

PATH="$(dirname "$(readlink -e "$0")"):$PATH"


function fetch_list_of_synced() {
    local s3_url=$1
    # NB there needs to be a / in the pattern for parsing the s3cmd ls output, we can just add it to 
    # the s3 url if there is none 
    if [[ ${s3_url: -1} != "/" ]]; then
        s3_url="$s3_url/"
    fi
    s3cmd -r ls "$s3_url" |\
        sed -r 's|[0-9-]+[[:space:]]+[0-9:]+[[:space:]]+[0-9]+[[:space:]]+'"$s3_url"'(.+)|\1|' |\
        sort
}

function list_all_local_files() {
    local -r source_dir=$1
    local -r include_tests=$2
    find "$source_dir" -type f $include_tests -printf '%P\n' | sort
}


while getopts "b:d" opt; do
    case $opt in
        b )
            # TODO check if number
            declare -r BATCH_SIZE=$OPTARG;;
        d ) 
            declare -r DRY_RUN=;;
	esac
done
shift $(expr $OPTIND - 1 )


source_dir=${1-}
if [[ -z $(readlink -e "$source_dir") ]]; then
    echo "[ERROR] Source directory missing $source_dir"
    exit 1
fi

include_tests=${2-}
if [[ -z $include_tests ]]; then
    echo "[ERROR] Include tests for finding candidates missing" >&2
    exit 1
fi

s3_target_url=${3-}
if [[ -z $s3_target_url ]]; then
    echo "[ERROR] S3 target url missing" >&2
    exit 1
fi


# NB --old-line-format="%L" will only output the line content, no ">" suffixes
# NB wrapping the diff call in an echo call will help with handling the return code from diff:
#   if there are differences, diff will always return 1 but we just want its output
candidates=$(echo "$(diff --new-line-format= --unchanged-line-format= --old-line-format="%L" \
        <(list_all_local_files "$source_dir" "$include_tests") \
        <(fetch_list_of_synced "$s3_target_url"))")

if [[ -v BATCH_SIZE ]] && [[ -n $candidates ]]; then
    echo "[INFO] Selecting batch of $BATCH_SIZE, full candidates count is $(wc -l <<<"$candidates")"
    candidates=$(head -n "$BATCH_SIZE" <<<"$candidates")
fi

if [[ -v DRY_RUN ]]; then
    echo "[INFO] Found $(wc -l <<<"$candidates") files to sync" >&2
    echo "$candidates"
    exit
fi

sync_files "$source_dir" "$s3_target_url" <<<"$candidates"